export enum sandzakCity {
  berane = 'Berane',
  brodarevo = 'Brodarevo',
  gusinje = 'Gusinje',
  novaVaros = 'Nova Varoš',
  noviPazar = 'Novi Pazar',
  petnjica = 'Petnjica',
  plav = 'Plav',
  pljevlja = 'Pljevlja',
  priboj = 'Priboj',
  prijePolje = 'Prijepolje',
  rozaje = 'Rožaje',
  sjenica = 'Sjenica',
  tutin = 'Tutin',
}
